# Site settings
en:
  title: The Chance Band - Official Website
  brand: Chance
  description: >
    Chance began its journey in 1996. As a group they led many hearts
    to Christ. They use their lyrics to inspire the young generation
    of today’s times. Take the Chance and listen.

ru:
  title: The Chance Band - Официальный сайт
  brand: Шанс
  description: >
    Группа “Шанс” начала свой путь в 1996 году. Мы верим, что через
    музыку можно сказать о вечном и главном. Для нас шанс это Голгофа
    быть услышанным.


email: chancebandmusic@gmail.com
baseurl: ""
url: "https://www.thechanceband.com"

collections:
- sections
- albums
- songs

donate:
- https://www.paypal.com/cgi-bin/webscr?cmd=_donations
- business=GFLE2AW7CJZ5W
- lc=US
- item_name=The%20Chance%20Band
- currency_code=USD
- bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted

social:
  facebook: https://www.facebook.com/chancebandmusic
  twitter: https://twitter.com/chancebandmusic
  youtube: https://www.youtube.com/channel/UCNKlcqmdt7kFJAytbtNed5Q
  google-plus: https://plus.google.com/+thechanceband101
  vk: https://vk.com/thechanceband

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, config.ru]

gems:
  - jekyll-assets
  - bootstrap-sass

assets:
  js_compressor:  uglifier
  css_compressor: sass
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
