# Site settings
en:
  title: Chance
  description: >
    Chance began its journey in 1996. As a group they led many hearts
    to Christ. They use their lyrics to inspire the young generation
    of today’s times. Take the Chance and listen.

ru:
  title: Шанс
  description: >
    Группа “Шанс” начала свой путь в 1996 году. Мы верим, что через
    музыку можно сказать о вечном и главном. Для нас шанс это Голгофа
    быть услышанным.


email: chancebandmusic@gmail.com
baseurl: ""
url: "https://www.thechanceband.com"

collections:
- sections
- albums
- songs

social:
  facebook: https://www.facebook.com/chancebandsongs
  twitter: https://twitter.com/chancebandsongs
  youtube: https://www.youtube.com/channel/UCyOswyvw8ugbS22ZSVop4bg
  google-plus: https://plus.google.com/108316022689360703562/posts
  pinterest: http://www.pinterest.com/sergshemyakin/

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock, config.ru]

gems:
  - jekyll-assets
  - bootstrap-sass

assets:
  js_compressor:  uglifier
  css_compressor: sass
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
